// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Autentica um usuário e retorna um token JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login de usuário",
                "parameters": [
                    {
                        "description": "Credenciais de login",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.AuthLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login bem-sucedido",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.AuthLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Credenciais inválidas",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Cria um novo usuário no sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Registro de novo usuário",
                "parameters": [
                    {
                        "description": "Dados do usuário",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.AuthRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Usuário registrado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/categories": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cria uma nova categoria de transação para o usuário autenticado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Criar categoria de transação",
                "parameters": [
                    {
                        "description": "Dados da categoria",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.CategoryCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Categoria criada com sucesso",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/goals": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cria uma nova meta financeira para o usuário autenticado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goals"
                ],
                "summary": "Criar meta financeira",
                "parameters": [
                    {
                        "description": "Dados da meta",
                        "name": "goal",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.GoalCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Meta criada com sucesso",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/goals/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Atualiza uma meta financeira existente do usuário autenticado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goals"
                ],
                "summary": "Atualizar meta financeira",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da meta",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados atualizados da meta",
                        "name": "goal",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.GoalUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Meta atualizada com sucesso",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/investments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista todos os investimentos do usuário autenticado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "investments"
                ],
                "summary": "Listar investimentos",
                "responses": {
                    "200": {
                        "description": "Lista de investimentos",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.InvestmentListResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cria um novo investimento para o usuário autenticado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "investments"
                ],
                "summary": "Criar investimento",
                "parameters": [
                    {
                        "description": "Dados do investimento",
                        "name": "investment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.InvestmentCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Investimento criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.InvestmentCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/investments/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Recupera os dados de um investimento específico do usuário autenticado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "investments"
                ],
                "summary": "Obter investimento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do investimento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dados do investimento",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.InvestmentSingleResponse"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Investimento não encontrado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove um investimento do usuário quando não há saldo pendente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "investments"
                ],
                "summary": "Excluir investimento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do investimento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Investimento excluído",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Requisição inválida",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Investimento não encontrado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/investments/{id}/contribution": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registra um aporte financeiro em um investimento existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "investments"
                ],
                "summary": "Realizar aporte",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do investimento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados do aporte",
                        "name": "contribution",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.InvestmentContributionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Aporte registrado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Investimento não encontrado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/investments/{id}/return": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtém lucro absoluto e percentual acumulado do investimento",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "investments"
                ],
                "summary": "Calcular retorno de investimento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do investimento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Retorno calculado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.InvestmentReturnResponse"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/investments/{id}/withdraw": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registra um resgate financeiro de um investimento existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "investments"
                ],
                "summary": "Realizar resgate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do investimento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados do resgate",
                        "name": "withdraw",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.InvestmentWithdrawRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Resgate realizado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Investimento não encontrado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/transactions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista todas as transações do usuário autenticado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Listar transações",
                "responses": {
                    "200": {
                        "description": "Lista de transações",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Fynance_internal_domain_transaction.Transaction"
                            }
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cria uma nova transação financeira para o usuário autenticado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Criar transação",
                "parameters": [
                    {
                        "description": "Dados da transação",
                        "name": "transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.TransactionCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Transação criada com sucesso",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.TransactionCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "Cria um novo usuário no sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Criar usuário",
                "parameters": [
                    {
                        "description": "Dados do usuário",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.UserCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Usuário criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/email": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Busca um usuário pelo seu email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Obter usuário por email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email do usuário",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dados do usuário",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Parâmetros inválidos",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Busca um usuário pelo seu ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Obter usuário por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do usuário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dados do usuário",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Atualiza os dados de um usuário (apenas o próprio usuário pode atualizar)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Atualizar usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do usuário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados atualizados do usuário",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.UserUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dados do usuário atualizados",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_domain_user.User"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Acesso negado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Exclui um usuário do sistema (apenas o próprio usuário pode se excluir)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Excluir usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do usuário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usuário excluído com sucesso",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.UserDeletionResponse"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Acesso negado",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/Fynance_internal_contracts.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Fynance_internal_contracts.AuthLoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "Fynance_internal_contracts.AuthLoginResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "Fynance_internal_contracts.AuthRegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "Fynance_internal_contracts.CategoryCreateRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "icon": {
                    "type": "string",
                    "maxLength": 50
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "Fynance_internal_contracts.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "Fynance_internal_contracts.GoalCreateRequest": {
            "type": "object",
            "required": [
                "category_id",
                "name",
                "target"
            ],
            "properties": {
                "category_id": {
                    "type": "string"
                },
                "end_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "target": {
                    "type": "number"
                }
            }
        },
        "Fynance_internal_contracts.GoalUpdateRequest": {
            "type": "object",
            "required": [
                "category_id",
                "name",
                "target"
            ],
            "properties": {
                "category_id": {
                    "type": "string"
                },
                "end_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "target": {
                    "type": "number"
                }
            }
        },
        "Fynance_internal_contracts.InvestmentContributionRequest": {
            "type": "object",
            "required": [
                "amount",
                "category_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "category_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            }
        },
        "Fynance_internal_contracts.InvestmentCreateRequest": {
            "type": "object",
            "required": [
                "initial_amount",
                "name",
                "type"
            ],
            "properties": {
                "category_id": {
                    "type": "string"
                },
                "initial_amount": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "return_rate": {
                    "type": "number"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "CDB",
                        "LCI",
                        "LCA",
                        "TESOURO_DIRETO",
                        "ACOES",
                        "FUNDOS",
                        "CRIPTOMOEDAS",
                        "PREVIDENCIA"
                    ]
                }
            }
        },
        "Fynance_internal_contracts.InvestmentCreateResponse": {
            "type": "object",
            "properties": {
                "investment": {
                    "$ref": "#/definitions/Fynance_internal_domain_investment.Investment"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "Fynance_internal_contracts.InvestmentListResponse": {
            "type": "object",
            "properties": {
                "investments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Fynance_internal_domain_investment.Investment"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "Fynance_internal_contracts.InvestmentReturnResponse": {
            "type": "object",
            "properties": {
                "profit": {
                    "type": "number"
                },
                "return_percentage": {
                    "type": "number"
                }
            }
        },
        "Fynance_internal_contracts.InvestmentSingleResponse": {
            "type": "object",
            "properties": {
                "investment": {
                    "$ref": "#/definitions/Fynance_internal_domain_investment.Investment"
                }
            }
        },
        "Fynance_internal_contracts.InvestmentWithdrawRequest": {
            "type": "object",
            "required": [
                "amount",
                "category_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "category_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            }
        },
        "Fynance_internal_contracts.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "Fynance_internal_contracts.TransactionCreateRequest": {
            "type": "object",
            "required": [
                "amount",
                "category_id",
                "date",
                "type"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "category_id": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "maxLength": 255
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "RECEIPT",
                        "EXPENSE",
                        "TRANSFER",
                        "GOALS",
                        "INVESTMENT",
                        "WITHDRAW"
                    ]
                }
            }
        },
        "Fynance_internal_contracts.TransactionCreateResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "transaction": {
                    "$ref": "#/definitions/Fynance_internal_domain_transaction.Transaction"
                }
            }
        },
        "Fynance_internal_contracts.UserCreateRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "plan": {
                    "type": "string",
                    "enum": [
                        "FREE",
                        "BASIC",
                        "PRO"
                    ]
                }
            }
        },
        "Fynance_internal_contracts.UserDeletionResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "Fynance_internal_contracts.UserUpdateRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "plan": {
                    "type": "string",
                    "enum": [
                        "FREE",
                        "BASIC",
                        "PRO"
                    ]
                }
            }
        },
        "Fynance_internal_domain_investment.Investment": {
            "type": "object",
            "properties": {
                "application_date": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "current_balance": {
                    "type": "number"
                },
                "id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "name": {
                    "type": "string"
                },
                "return_balance": {
                    "type": "number"
                },
                "return_rate": {
                    "type": "number"
                },
                "type": {
                    "$ref": "#/definitions/Fynance_internal_domain_investment.Types"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "Fynance_internal_domain_investment.Types": {
            "type": "string",
            "enum": [
                "CDB",
                "LCI",
                "LCA",
                "TESOURO_DIRETO",
                "ACOES",
                "FUNDOS",
                "CRIPTOMOEDAS",
                "PREVIDENCIA"
            ],
            "x-enum-varnames": [
                "TypeCDB",
                "TypeLCI",
                "TypeLCA",
                "TypeTesouro",
                "TypeAcoes",
                "TypeFundos",
                "TypeCripto",
                "TypePrevidencia"
            ]
        },
        "Fynance_internal_domain_transaction.Transaction": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "category_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "investment_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "type": {
                    "$ref": "#/definitions/Fynance_internal_domain_transaction.Types"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "Fynance_internal_domain_transaction.Types": {
            "type": "string",
            "enum": [
                "RECEIPT",
                "EXPENSE",
                "TRANSFER",
                "GOALS",
                "INVESTMENT",
                "WITHDRAW"
            ],
            "x-enum-varnames": [
                "Receipt",
                "Expense",
                "Transfer",
                "Goals",
                "Investment",
                "Withdraw"
            ]
        },
        "Fynance_internal_domain_user.Plan": {
            "type": "string",
            "enum": [
                "FREE",
                "BASIC",
                "PRO"
            ],
            "x-enum-varnames": [
                "PlanFree",
                "PlanBasic",
                "PlanPro"
            ]
        },
        "Fynance_internal_domain_user.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "plan": {
                    "$ref": "#/definitions/Fynance_internal_domain_user.Plan"
                },
                "plan_since": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Utilize \"Bearer \u003ctoken\u003e\" no header Authorization",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Fynance API",
	Description:      "API de gestão financeira pessoal (Fynance)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
